// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC6I-1-EdT-3RzwoW5Xfg-gmHLryRRv7I',
    appId: '1:322547275203:web:499f42356d52940db01976',
    messagingSenderId: '322547275203',
    projectId: 'team-ion-21',
    authDomain: 'team-ion-21.firebaseapp.com',
    storageBucket: 'team-ion-21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnm47fVZj6G3ZjotpxJQbAx7LkOnP5b2Q',
    appId: '1:322547275203:android:71125774a3cc9a7eb01976',
    messagingSenderId: '322547275203',
    projectId: 'team-ion-21',
    storageBucket: 'team-ion-21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOkMFXVk9Yz4TwbpYDoMgvq10S-tr112M',
    appId: '1:322547275203:ios:85e5ad11c5576573b01976',
    messagingSenderId: '322547275203',
    projectId: 'team-ion-21',
    storageBucket: 'team-ion-21.appspot.com',
    iosClientId: '322547275203-fqmlq72li9gns1cejoa7r3ff216nguj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProjectManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOkMFXVk9Yz4TwbpYDoMgvq10S-tr112M',
    appId: '1:322547275203:ios:85e5ad11c5576573b01976',
    messagingSenderId: '322547275203',
    projectId: 'team-ion-21',
    storageBucket: 'team-ion-21.appspot.com',
    iosClientId: '322547275203-fqmlq72li9gns1cejoa7r3ff216nguj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProjectManageApp',
  );
}
